# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  crane_x7_gripper_finger_a_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: true
    max_acceleration: 4.4
  crane_x7_gripper_finger_b_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: true
    max_acceleration: 4.4
  crane_x7_lower_arm_fixed_part_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: true
    max_acceleration: 4.4
  crane_x7_lower_arm_revolute_part_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: true
    max_acceleration: 4.4
  crane_x7_shoulder_fixed_part_pan_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: true
    max_acceleration: 4.4
  crane_x7_shoulder_revolute_part_tilt_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: true
    max_acceleration: 4.4
  crane_x7_upper_arm_revolute_part_rotate_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: true
    max_acceleration: 4.4
  crane_x7_upper_arm_revolute_part_twist_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: true
    max_acceleration: 4.4
  crane_x7_wrist_joint:
    has_velocity_limits: true
    max_velocity: 4.81710873
    has_acceleration_limits: true
    max_acceleration: 4.4